### ISSUE TITLE
无法显示艺术家参考图片

### ISSUE THREAD

**Issue by didoll-john** [ZHO-ZHO-ZHO/ComfyUI-ArtGallery#16]
<img width="1152" alt="image" src="https://github.com/user-attachments/assets/16bace62-a729-401b-97c9-7cd4fb10e011">

但是没有报错，只是不显示

**Comment by didoll-john** [comment]
反复重启ComfyUI和刷新浏览器均无效，依然无法显示预览

**Comment by alanhzh** [comment]
https://github.com/alanhzh/ComfyUI-ArtGallery-updates/tree/main
<img width="1552" alt="aaa" src="https://github.com/user-attachments/assets/f7267e47-f870-4dae-ac1d-e7bd4402bb61">

**Comment by alanhzh** [comment]
<img width="1332" alt="bbb" src="https://github.com/user-attachments/assets/be6d83a6-5a63-430a-ae0c-ad9f759750f8">

**Comment by didoll-john** [comment]
# 文件路径
current_dir = os.path.dirname(os.path.abspath(__file__))
uploadimg_js_file_path = os.path.join(current_dir, '../../web/assets/index-DJRcbqp_.js')

comfyui的原始文件里不存在这个js，也不存在这个PR里后续的index-xxxx.js，你使用的是什么版本？

**Comment by didoll-john** [comment]
> https://github.com/alanhzh/ComfyUI-ArtGallery-updates/tree/main <img alt="aaa" width="1552" src="https://private-user-images.githubusercontent.com/4001312/358562761-f7267e47-f870-4dae-ac1d-e7bd4402bb61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTU3MDYsIm5iZiI6MTcyMzgxNTQwNiwicGF0aCI6Ii80MDAxMzEyLzM1ODU2Mjc2MS1mNzI2N2U0Ny1mODcwLTRkYWUtYWMxZC1lN2JkNDQwMmJiNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTMzNjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkxNjgzNTBlOGFjMmIxMDNmNzEwY2EwN2M1M2M3NDI0NWJkMmZlZGYwNDNmZDIwYzk3ODY4ZGM4N2M3ZTU3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.61uTQ1a7LVrkGxaKHZINClBz-X-Wg1Ch88k90ORx5oA">

感谢大佬！

**Comment by pto2k** [comment]
> <img alt="bbb" width="1332" src="https://private-user-images.githubusercontent.com/4001312/358563493-be6d83a6-5a63-430a-ae0c-ad9f759750f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDQzNjQsIm5iZiI6MTcyMzkwNDA2NCwicGF0aCI6Ii80MDAxMzEyLzM1ODU2MzQ5My1iZTZkODNhNi01YTYzLTQzMGEtYWUwYy1hZDlmNzU5NzUwZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTQxNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY2YTRhZmFjNTlmYWE0M2NmMDRhMzNiMGM3OTczZDc5MDA4ZDQ5Njg5NDJiOTU3ZWNiMjNjMzhlOTZkNmE0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rHUP856zrgcyPHOlDbJeLq8DTp6G2Jybv1obi2jXmdM">

请问
1. 新分支的修改应该如何使用？是把新的 __init__.py 覆盖到原先的目录里面吗？我试了一下会报错
2. 截图的设置界面没看到过，是用哪个扩展变成这样的吗？ 
谢谢

**Comment by didoll-john** [comment]
> > <img alt="bbb" width="1332" src="https://private-user-images.githubusercontent.com/4001312/358563493-be6d83a6-5a63-430a-ae0c-ad9f759750f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MDQzNjQsIm5iZiI6MTcyMzkwNDA2NCwicGF0aCI6Ii80MDAxMzEyLzM1ODU2MzQ5My1iZTZkODNhNi01YTYzLTQzMGEtYWUwYy1hZDlmNzU5NzUwZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTQxNDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY2YTRhZmFjNTlmYWE0M2NmMDRhMzNiMGM3OTczZDc5MDA4ZDQ5Njg5NDJiOTU3ZWNiMjNjMzhlOTZkNmE0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rHUP856zrgcyPHOlDbJeLq8DTp6G2Jybv1obi2jXmdM">
> 
> 请问
> 
> 1. 新分支的修改应该如何使用？是把新的 **init**.py 覆盖到原先的目录里面吗？我试了一下会报错
> 2. 截图的设置界面没看到过，是用哪个扩展变成这样的吗？
>    谢谢

把ComfyUI更新到最新版

**Comment by chunhui-l** [comment]
![微信截图_20241019174552](https://github.com/user-attachments/assets/f519c50f-dbc9-451c-9d6b-bb653bbe8a7f)
ComfyUI-ArtGallery无法显示，有朋友知道什么原因吗
