### ISSUE TITLE
'gbk' codec can't decode byte 0x80 in position 336: illegal multibyte sequence

### ISSUE THREAD

**Issue by chdldy** [ZHO-ZHO-ZHO/ComfyUI-ArtGallery#6]
E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ArtGallery\../../web/extensions/core/uploadImage.js
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ArtGallery\__init__.py", line 56, in <module>
    modify_js_file(uploadimg_js_file_path, new_js_content)
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ArtGallery\__init__.py", line 6, in modify_js_file
    content = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 336: illegal multibyte sequence

Cannot import E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ArtGallery module for custom nodes: 'gbk' codec can't decode byte 0x80 in position 336: illegal multibyte sequence

**Comment by LeroyDaydreamer** [comment]
That is most likely the same issue discussed in the other two threads, the missing UTF-8 handling. See [this](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery/issues/2#issuecomment-1913558408) how to fix it. Keep in mind that whenever you update the custom nodes, it might be broken again and some core .js files get wiped, so you may not even see the ComfyUI's GUI anymore until you update ComfyUI.

**Comment by zmwv823** [comment]
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery/assets/13308350/701b3beb-2ea6-4f3a-9f2b-79bc3a3bb92e)
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery/assets/13308350/620d6ae5-2dc7-4a0e-b002-fb9c746a14f0)
Try this:
- **Change error files encoder into utf8,fast and convenient, without code change.**

**Comment by chdldy** [comment]
> ![image](https://private-user-images.githubusercontent.com/13308350/302858247-701b3beb-2ea6-4f3a-9f2b-79bc3a3bb92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTgyNDctNzAxYjNiZWItMmVhNi00ZjNhLTlmMmItNzliYzNhM2JiOTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYmEwODE0ODAzN2NlYTBmYWQ3YTI0MGFhOThjNWRmNzI2NmYxNzI5ZjA5ZGIyYjU5MGE4YTVlZTYyY2VmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2ASM3hDRNu7Cx32urlATC0bH-RbL-hd0WtkgnW9pF4) ![image](https://private-user-images.githubusercontent.com/13308350/302858630-620d6ae5-2dc7-4a0e-b002-fb9c746a14f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTg2MzAtNjIwZDZhZTUtMmRjNy00YTBlLWIwMDItZmI5Yzc0NmExNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MjU3ZjYyNGZiM2U4ZmRmYzg0NjRiYzkwZmFhZTE5ZDI1ZDAwZTliMDhlOTNhMDk3YjkwMDc3OGE4YzRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDWrMX9F-6-RqPcNnvoZVviyEkMWoNsxhcupl2W0g7I) Try this:
> 
> * **Change error files encoder into utf8,fast and convenient, without code change.**

Thank you, this operation works

**Comment by ZTWY35** [comment]
> > ![image](https://private-user-images.githubusercontent.com/13308350/302858247-701b3beb-2ea6-4f3a-9f2b-79bc3a3bb92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTgyNDctNzAxYjNiZWItMmVhNi00ZjNhLTlmMmItNzliYzNhM2JiOTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYmEwODE0ODAzN2NlYTBmYWQ3YTI0MGFhOThjNWRmNzI2NmYxNzI5ZjA5ZGIyYjU5MGE4YTVlZTYyY2VmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2ASM3hDRNu7Cx32urlATC0bH-RbL-hd0WtkgnW9pF4) ![image](https://private-user-images.githubusercontent.com/13308350/302858630-620d6ae5-2dc7-4a0e-b002-fb9c746a14f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTg2MzAtNjIwZDZhZTUtMmRjNy00YTBlLWIwMDItZmI5Yzc0NmExNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MjU3ZjYyNGZiM2U4ZmRmYzg0NjRiYzkwZmFhZTE5ZDI1ZDAwZTliMDhlOTNhMDk3YjkwMDc3OGE4YzRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDWrMX9F-6-RqPcNnvoZVviyEkMWoNsxhcupl2W0g7I) Try this:
> > 
> > * **Change error files encoder into utf8,fast and convenient, without code change.将错误文件编码器修改为utf8，快速方便，无需更改代码。**
> 
> Thank you, this operation works

我这已经看不到图片了，我也一样碰到这个问题，现没解决呢，我把D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery\__init__.py 文件 编码改为UTF-8，还是报同样的错。

I'm still unable to see images, I've encountered the same issue and have yet to find a solution. After changing the encoding of the file D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery\__init__.py to UTF-8, I'm still getting the same error.

**Comment by zmwv823** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/13308350/302858247-701b3beb-2ea6-4f3a-9f2b-79bc3a3bb92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTgyNDctNzAxYjNiZWItMmVhNi00ZjNhLTlmMmItNzliYzNhM2JiOTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYmEwODE0ODAzN2NlYTBmYWQ3YTI0MGFhOThjNWRmNzI2NmYxNzI5ZjA5ZGIyYjU5MGE4YTVlZTYyY2VmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2ASM3hDRNu7Cx32urlATC0bH-RbL-hd0WtkgnW9pF4) ![image](https://private-user-images.githubusercontent.com/13308350/302858630-620d6ae5-2dc7-4a0e-b002-fb9c746a14f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTg2MzAtNjIwZDZhZTUtMmRjNy00YTBlLWIwMDItZmI5Yzc0NmExNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MjU3ZjYyNGZiM2U4ZmRmYzg0NjRiYzkwZmFhZTE5ZDI1ZDAwZTliMDhlOTNhMDk3YjkwMDc3OGE4YzRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDWrMX9F-6-RqPcNnvoZVviyEkMWoNsxhcupl2W0g7I) Try this:
> > > 
> > > * **Change error files encoder into utf8,fast and convenient, without code change.将错误文件编码器修改为utf8，快速方便，无需更改代码。**
> > 
> > 
> > Thank you, this operation works
> 
> 我这已经看不到图片了，我也一样碰到这个问题，现没解决呢，我把D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery__init__.py 文件 编码改为UTF-8，还是报同样的错。
> 
> I'm still unable to see images, I've encountered the same issue and have yet to find a solution. After changing the encoding of the file D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery__init__.py to UTF-8, I'm still getting the same error.

The best way is to change code in `__init__.py`, add `, encoding='UTF-8'` after 'r' or 'w':
- lines need to modify: 5-18-61-86-133-152.
- An example:
```
with open(file_path, 'r', encoding='UTF-8') as file:
```
That's y i delete the comment.

**Comment by ZTWY35** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/13308350/302858247-701b3beb-2ea6-4f3a-9f2b-79bc3a3bb92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTgyNDctNzAxYjNiZWItMmVhNi00ZjNhLTlmMmItNzliYzNhM2JiOTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYmEwODE0ODAzN2NlYTBmYWQ3YTI0MGFhOThjNWRmNzI2NmYxNzI5ZjA5ZGIyYjU5MGE4YTVlZTYyY2VmOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A2ASM3hDRNu7Cx32urlATC0bH-RbL-hd0WtkgnW9pF4) ![image](https://private-user-images.githubusercontent.com/13308350/302858630-620d6ae5-2dc7-4a0e-b002-fb9c746a14f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTM3MzIsIm5iZiI6MTcwODMxMzQzMiwicGF0aCI6Ii8xMzMwODM1MC8zMDI4NTg2MzAtNjIwZDZhZTUtMmRjNy00YTBlLWIwMDItZmI5Yzc0NmExNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAzMzAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MjU3ZjYyNGZiM2U4ZmRmYzg0NjRiYzkwZmFhZTE5ZDI1ZDAwZTliMDhlOTNhMDk3YjkwMDc3OGE4YzRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDWrMX9F-6-RqPcNnvoZVviyEkMWoNsxhcupl2W0g7I) Try this:
> > > > 
> > > > * **Change error files encoder into utf8,fast and convenient, without code change.将错误文件编码器修改为utf8，快速方便，无需更改代码。**
> > > 
> > > 
> > > Thank you, this operation works
> > 
> > 
> > 我这已经看不到图片了，我也一样碰到这个问题，现没解决呢，我把D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery__init__.py 文件 编码改为UTF-8，还是报同样的错。
> > I'm still unable to see images, I've encountered the same issue and have yet to find a solution. After changing the encoding of the file D:\Program Files\ComfyUI_Mie_V2\ComfyUI\custom_nodes\ComfyUI-ArtGallery__init__.py to UTF-8, I'm still getting the same error.
> 
> The best way is to change code in , add after 'r' or 'w':`__init__.py``, encoding='UTF-8'`
> 
> * lines need to modify: 5-18-61-86-133-152.
> * An example:
> 
> ```
> with open(file_path, 'r', encoding='UTF-8') as file:
> ```
> 
> That's y i delete the comment.

Thank you very much for your help, the problem has been resolved, thank you.
